Prepare cupertino_http 1.0.0 release

diff --git a/.github/workflows/cupertino.yml b/.github/workflows/cupertino.yml
--- a/.github/workflows/cupertino.yml
+++ b/.github/workflows/cupertino.yml
@@ -45,7 +45,10 @@ jobs:
   test:
     # Test package:cupertino_http use flutter integration tests.
     needs: analyze
-    name: "Build and test (disabled!)"
+    name: "Build and test"
+    strategy:
+      matrix:
+        flutter-version: ["3.10.0", "any"]
     runs-on: macos-latest
     defaults:
       run:
@@ -57,10 +60,10 @@ jobs:
           model: 'iPhone 8'
       - uses: subosito/flutter-action@v2
         with:
-          # TODO: Change to 'stable' when a release version of flutter
-          # pins version 1.21.1 or later of 'package:test'
-          channel: 'master'
+          flutter-version: ${{ matrix.flutter-version }}
+          channel: stable
       - name: Run tests
-        # TODO: Renable tests when https://github.com/dart-lang/http/issues/938
-        # is fixed.
-        run: echo flutter test integration_test/
+        # TODO: Remove the retries when
+        # https://github.com/flutter/flutter/issues/121231 is fixed.
+        # See https://github.com/dart-lang/http/issues/938 for context.
+        run: for i in {1..5}; do flutter test integration_test/main.dart && break || echo "Retry $i"; done
